name: dis

services:
  kafka:
    image: apache/kafka-native
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT

      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091

      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-network

  service-master:
    build:
      context: ./master
      dockerfile: Dockerfile
    container_name: master
    networks:
      backend:
      kafka-network:

  service-scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    container_name: scraper
    networks:
      kafka-network:

  service-reducer:
    build:
      context: ./reducer
      dockerfile: Dockerfile
    container_name: reducer
    networks:
      kafka-network:

  test-service:
    image: curlimages/curl
    command: [ "tail", "-f", "/dev/null" ]
    networks:
      backend:

networks:
  backend:
    driver: bridge
  kafka-network:
    driver: bridge