server:
  port: 8888

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: ["http://34.171.39.26:3000", "http://gamey.gcp:3000", "http://localhost:3000"]
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers:
                  - "*"
                allow-credentials: true
          routes:
            - id: gamedata
              uri: lb://GAME.DATA
              predicates:
                - Path=/gamedata/**
              filters:
                - StripPrefix=1
            - id: discovery
              uri: lb://WORKER.DISCOVERY
              predicates:
                - Path=/discovery/**
              filters:
                - StripPrefix=1
            - id: details
              uri: lb://WORKER.DETAIL
              predicates:
                - Path=/details/**
              filters:
                - StripPrefix=1
            - id: aggregator
              uri: lb://AGGREGATOR
              predicates:
                - Path=/aggregator/**
              filters:
                - StripPrefix=1
  kafka:
    bootstrap-servers: PLAINTEXT://kafka:9092

logging:
  level:
    web: trace
    reactor.netty.http.client: info
    reactor.netty.http.server: info

eureka:
  client:
    service-url:
      defaultZone: http://eureka-peer1:8761/eureka/,http://eureka-peer2:8762/eureka/
    enabled: true
