export const games = [
  {
    id: 1,
    title: "The Last of Us Part II",
    platform: ["PS4", "PS5"],
    genre: "Action",
    image: "/tlou.jpg",
    rating: 4.8,
    reviews: 1250,
    prices: [
      { store: "PlayStation Store", price: 39.99, url: "#" },
      { store: "Amazon", price: 34.99, url: "#" },
      { store: "GameStop", price: 29.99, url: "#" },
    ],
    comments: [
      { username: "GamerAlex", text: "Absolutely stunning story and gameplay!" },
      { username: "Lara89", text: "Emotional rollercoaster, highly recommend." },
      { username: "PSFanatic", text: "Graphically amazing, a must-play for PS fans." },
    ],
  },
  {
    id: 2,
    title: "Cyberpunk 2077",
    platform: ["PC", "PS4", "PS5"],
    genre: "RPG",
    image: "/cyberpunk.jpg",
    rating: 4.2,
    reviews: 2100,
    prices: [
      { store: "Steam", price: 29.99, url: "#" },
      { store: "Epic Games", price: 24.99, url: "#" },
      { store: "GOG", price: 27.99, url: "#" },
    ],
    comments: [
      { username: "NeoRunner", text: "Great world, immersive story." },
      { username: "TechGeek", text: "Some bugs at launch but fun gameplay." },
      { username: "RPGlover", text: "Loved the side quests and characters." },
    ],
  },
  {
    id: 3,
    title: "Resident Evil 4",
    platform: ["PC", "PS4", "PS5"],
    genre: "Horror",
    image: "/resident.jpg",
    rating: 4.9,
    reviews: 890,
    prices: [
      { store: "Steam", price: 59.99, url: "#" },
      { store: "PlayStation Store", price: 59.99, url: "#" },
      { store: "Amazon", price: 54.99, url: "#" },
    ],
    comments: [
      { username: "HorrorFan", text: "Classic horror done perfectly!" },
      { username: "Survivor23", text: "The tension is real, loved it!" },
      { username: "GamerX", text: "One of the best remakes I've played." },
    ],
  },
  {
    id: 4,
    title: "God of War",
    platform: ["PC", "PS4", "PS5"],
    genre: "Action",
    image: "/godofwar.jpg",
    rating: 4.7,
    reviews: 1680,
    prices: [
      { store: "Steam", price: 49.99, url: "#" },
      { store: "PlayStation Store", price: 39.99, url: "#" },
      { store: "Epic Games", price: 44.99, url: "#" },
    ],
    comments: [
      { username: "KratosFan", text: "Incredible story and combat system!" },
      { username: "MythHunter", text: "Loved exploring Norse mythology." },
      { username: "ActionGamer", text: "Intense battles and amazing visuals." },
    ],
  },
  {
    id: 5,
    title: "Phasmophobia",
    platform: ["PC"],
    genre: "Horror",
    image: "/phasm.jpg",
    rating: 4.3,
    reviews: 750,
    prices: [
      { store: "Steam", price: 13.99, url: "#" },
      { store: "Humble Bundle", price: 12.99, url: "#" },
    ],
    comments: [
      { username: "GhostHunter", text: "Terrifying multiplayer experience!" },
      { username: "ScaredyCat", text: "Great atmosphere and spooky sounds." },
      { username: "TeamPlayer", text: "Fun to play with friends." },
    ],
  },
  {
    id: 6,
    title: "Spider-Man: Miles Morales",
    platform: ["PS4", "PS5"],
    genre: "Action",
    image: "/spiderman.jpg",
    rating: 4.6,
    reviews: 920,
    prices: [
      { store: "PlayStation Store", price: 49.99, url: "#" },
      { store: "Amazon", price: 44.99, url: "#" },
      { store: "Best Buy", price: 47.99, url: "#" },
    ],
    comments: [
      { username: "WebSlinger", text: "Amazing swinging mechanics!" },
      { username: "MarvelFan", text: "Storyline is heartwarming and fun." },
      { username: "PSGamer", text: "Visuals and gameplay are top-notch." },
    ],
  },
 {
    id: 7,
    title: "Horizon Forbidden West",
    platform: ["PS4", "PS5"],
    genre: "Action RPG",
    image: "/horizon.jpg",
    rating: 4.8,
    reviews: 1320,
    prices: [
      { store: "PlayStation Store", price: 59.99, url: "#" },
      { store: "Amazon", price: 54.99, url: "#" },
    ],
    comments: [
      { username: "AloyFan", text: "Stunning visuals and epic story!" },
      { username: "RPGMaster", text: "Gameplay is smooth and engaging." },
      { username: "TechGamer", text: "Loved the exploration and mechanics." },
    ],
  },
  {
    id: 8,
    title: "Elden Ring",
    platform: ["PC", "PS4", "PS5", "Xbox One", "Xbox Series X"],
    genre: "RPG",
    image: "/elden.jpg",
    rating: 4.9,
    reviews: 2450,
    prices: [
      { store: "Steam", price: 59.99, url: "#" },
      { store: "Amazon", price: 57.99, url: "#" },
      { store: "PlayStation Store", price: 59.99, url: "#" },
    ],
    comments: [
      { username: "SoulsFan", text: "Challenging and rewarding experience!" },
      { username: "OpenWorldGamer", text: "Huge world, so many secrets!" },
      { username: "RPGAddict", text: "Best RPG I've played in years." },
    ],
  },
  {
    id: 9,
    title: "Stardew Valley",
    platform: ["PC", "PS4", "PS5", "Switch", "Xbox One"],
    genre: "Simulation",
    image: "/stardew.png",
    rating: 4.7,
    reviews: 1850,
    prices: [
      { store: "Steam", price: 14.99, url: "#" },
      { store: "GOG", price: 14.99, url: "#" },
      { store: "Switch eShop", price: 14.99, url: "#" },
    ],
    comments: [
      { username: "FarmLover", text: "Addictive and relaxing!" },
      { username: "PixelFan", text: "Charming graphics and gameplay." },
      { username: "DailyGamer", text: "Perfect game to unwind." },
    ],
  },
  {
    id: 10,
    title: "Godfall",
    platform: ["PC", "PS5"],
    genre: "Action RPG",
    image: "/godfall.jpg",
    rating: 4.1,
    reviews: 620,
    prices: [
      { store: "Epic Games", price: 39.99, url: "#" },
      { store: "Steam", price: 39.99, url: "#" },
    ],
    comments: [
      { username: "LootHunter", text: "Cool combat system but repetitive." },
      { username: "GearFan", text: "Love the armor sets and visuals." },
      { username: "ActionGamer", text: "Fun co-op experience!" },
    ],
  },
];