# --- Stage 1: Build the application ---
FROM gradle:8.9.0-jdk21-alpine AS build

WORKDIR /home/gradle/src

COPY --chown=gradle:gradle . .

RUN gradle build --no-daemon


# --- Stage 2: Create the final production image ---
FROM openjdk:21-slim

EXPOSE 8888

RUN mkdir /app
RUN mkdir /cache

COPY ./okhttp-cache /okhttp-cache
COPY --from=build /home/gradle/src/build/libs/*.jar /app/application.jar

ENTRYPOINT ["java", "-jar", "/app/application.jar"]
